### ISSUE TITLE
Missing Dependency: pacman-contrib

### ISSUE THREAD

**Issue by git-dc** [aericson/aarchup#15]
`/usr/bin/checkupdates` was moved to `pacman-contrib` about two years ago. `pacman-contrib` should be added a dependency.

**Comment by aericson** [comment]
This is no longer maintained see:
https://aur.archlinux.org/packages/aarchup/
https://gitlab.com/artafinde/aarchup/

**Comment by git-dc** [comment]
My bad, should have paid better attention which repo I am commenting under. I see it is in the dependencies list now. Thanks for the links.
