### ISSUE TITLE
Update for systemd timer

### ISSUE THREAD

**Issue by orschiro** [aericson/aarchup#2]
Hi @aericson,

Many thanks for `aarchup`. I was precisely looking for a small OSD notification program that only does this. Instead of cron I would like to use [systemd Timer](https://wiki.archlinux.org/index.php/Systemd/Timers), however.

Is it possible to add that support?

Many thanks in advance!

Robert

**Comment by aericson** [comment]
I'll look into it

**Comment by orschiro** [comment]
Thanks for your quick reply!

Let me know if I can help you testing.

~ Robert

On 01/21/2015 05:22 PM, André Ericson wrote:
>
> I'll look into it
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/aericson/aarchup/issues/2#issuecomment-70867782>.
>

-- 
Sharing my passion & inspiration for

#sustasty lifestyles #transitions
#opensource #degrowth / Love
#bouldering

Flying is old-school and the
world cannot be saved part-time

Co-Creator of @MindfulMeerkats

www.robert.orzanna.de
twitter.com/@orschiro

**Comment by aericson** [comment]
Could you try this PKGBUILD:
https://gist.githubusercontent.com/aericson/419c5d7a8c5c7c39deca/raw/fd88b5ad6633620685f627fcecf03dfd05376cb1/PKGBUILD

**Comment by orschiro** [comment]
Thank you!

The package installed correctly.

`/etc/systemd/system/aarchup.timer` description should be updated I guess:
```
Description=Run foo every minute
```

However, it fails to start:
```
❯ sudo systemctl start /etc/systemd/system/aarchup.timer
Failed to start etc-systemd-system-aarchup.timer.mount: Unit etc-systemd-system-aarchup.timer.mount failed to load: No such file or directory.
```
```                                                                                
❯ sudo systemctl status /etc/systemd/system/aarchup.timer
● etc-systemd-system-aarchup.timer.mount
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
```
```
❯ sudo systemctl status /etc/systemd/system/aarchup.service
● etc-systemd-system-aarchup.service.mount
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
```

**Comment by aericson** [comment]
My bad there, I updated my comment with the correct command

**Comment by orschiro** [comment]
Thanks!

Now it starts without any issue. I will wait for the first update 
notification to appear (currently my system is up to date) and will 
report back.

~ Robert
On 01/22/2015 04:03 PM, André Ericson wrote:
>
> My bad there, I updated my comment with the correct command
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/aericson/aarchup/issues/2#issuecomment-71033134>.
>

-- 
Sharing my passion & inspiration for

#sustasty lifestyles #transitions
#opensource #degrowth / Love
#bouldering

Flying is old-school and the
world cannot be saved part-time

Co-Creator of @MindfulMeerkats

www.robert.orzanna.de
twitter.com/@orschiro

**Comment by aericson** [comment]
@orschiro all good?

**Comment by orschiro** [comment]
It is working, thanks very much!


On 01/24/2015 07:01 PM, André Ericson wrote:
>
> @orschiro <https://github.com/orschiro> all good?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/aericson/aarchup/issues/2#issuecomment-71329683>.
>

-- 
Sharing my passion & inspiration for

#sustasty lifestyles #transitions
#opensource #degrowth / Love
#bouldering

Flying is old-school and the
world cannot be saved part-time

Co-Creator of @MindfulMeerkats

www.robert.orzanna.de
twitter.com/@orschiro

**Comment by aericson** [comment]
No problem, will update to AUR when I update docs.
