### ISSUE TITLE
Use dconf-service for environ info in noxaarchup.sh

### ISSUE THREAD

**Issue by Ketsuban** [aericson/aarchup#5]
`gconf-helper` is provided by the `pulseaudio` package; I don't use `pulseaudio`, so I don't have `gconf-helper` running, so the script fails since it falls back on its own PID and it's run as `root`. I do however use `dconf`, which provides an executable called `dconf-service` whose environ data is the same.

**Comment by aericson** [comment]
Interesting considering that an user reported at https://aur.archlinux.org/packages/aarchup/ that the /proc/self/environ worked for him. That's the only reason I added it at all.

Anyway I will look into it.
Thanks for the input.

**Comment by Ketsuban** [comment]
Thinking about it, they may have activated the timer with the `--user` switch, so the script is being run with their user-account credentials. I'm not, which is why it's run as `root`.

**Comment by aericson** [comment]
Updated.
