### ISSUE TITLE
No archlogo.png in resulting package

### ISSUE THREAD

**Issue by leonth** [aericson/aarchup#6]
I installed the package via AUR but the resulting .xz package does not have archlogo.png in it, only archlogo.svg.

In the end, I need to change the content of `/usr/share/aarchup/aarchupstartup.sh`:

```
- /usr/bin/aarchup --loop-time 60 --icon /usr/share/aarchup/archlogo.png &
+ /usr/bin/aarchup --loop-time 60 --icon /usr/share/aarchup/archlogo.svg &
```

**Comment by aericson** [comment]
I have added a .png image as more environments support it.
Thanks for reporting it.
